import tensorflow as tf
import numpy as np

model = None
output_class = ["Battery", "Pakaian", "E-limbah", "Kaca", "Bola Lampu", "Metal", "Organic", "Kertas", "Plastic"]
data = {
"Battery":
	["Daur ulang baterai adalah kegiatan daur ulang yang bertujuan untuk mengurangi jumlah baterai yang dibuang sebagai sampah kota. Baterai mengandung sejumlah logam berat dan bahan kimia beracun dan membuangnya dengan proses yang sama seperti limbah rumah tangga biasa telah menimbulkan kekhawatiran akan pencemaran tanah dan polusi air.<br><br> Sebagian besar jenis baterai dapat didaur ulang. Namun, beberapa baterai didaur ulang lebih mudah daripada yang lain, seperti baterai otomotif timbal-asam (hampir 90% didaur ulang) dan sel kancing (karena nilai dan toksisitas bahan kimianya). Nikel-kadmium (Ni-Cd) yang dapat diisi ulang, hidrida logam nikel (Ni-MH), lithium-ion (Li-ion) dan nikel-seng (Ni-Zn), juga dapat didaur ulang. Saat ini tidak ada opsi daur ulang hemat biaya yang tersedia untuk baterai alkaline sekali pakai, meskipun pedoman pembuangan konsumen berbeda-beda di setiap wilayah.",
	"4XOAGNzWvqY", "oKFOqMZmuA8"],
"Pakaian":
	["Daur ulang tekstil adalah proses pemulihan serat, benang atau kain dan pengolahan ulang bahan tekstil menjadi produk yang berguna. Produk limbah tekstil dikumpulkan dari sumber yang berbeda dan kemudian dipilah dan diproses tergantung pada kondisi, komposisi, dan nilai jualnya. Hasil akhir dari pemrosesan ini dapat bervariasi, mulai dari produksi energi dan bahan kimia hingga produk pakaian baru.<br><br>Karena tren konsumsi berlebihan dan timbulan limbah dalam budaya mode global belakangan ini, daur ulang tekstil telah menjadi kunci fokus upaya keberlanjutan di seluruh dunia. Globalisasi telah memunculkan tren \"fast fashion\" di mana pakaian dianggap oleh banyak konsumen sebagai barang sekali pakai karena harganya yang semakin murah. Perkembangan teknologi daur ulang telah memungkinkan industri tekstil menghasilkan sejumlah besar produk yang menghabiskan sumber daya alam.",
	"Bhi7S06pwv4", "IHPBJySIXZw"],
"E-limbah":
	["Limbah elektronik atau e-waste menggambarkan perangkat listrik atau elektronik yang dibuang. Barang elektronik bekas yang ditujukan untuk perbaikan, penggunaan kembali, penjualan kembali, daur ulang penyelamatan melalui pemulihan material, atau pembuangan juga dianggap limbah elektronik. Pemrosesan limbah elektronik secara tidak resmi di negara berkembang dapat menyebabkan dampak buruk bagi kesehatan manusia dan pencemaran lingkungan.<br><br>Komponen skrap elektronik, seperti CPU, mengandung bahan yang berpotensi berbahaya seperti timbal, kadmium, berilium, atau penghambat api brominasi . Daur ulang dan pembuangan limbah elektronik dapat menimbulkan risiko yang signifikan terhadap kesehatan pekerja dan komunitasnya.<br><br>Limbah elektronik atau limbah elektronik tercipta saat produk elektronik dibuang setelah masa pakainya berakhir. Ekspansi teknologi yang cepat dan masyarakat yang didorong oleh konsumsi menghasilkan limbah elektronik dalam jumlah yang sangat besar setiap menitnya.",
	"aUwFXDLOFO0","w0ikFMTuS9c"],
"Kaca":
	["Daur ulang kaca adalah pengolahan limbah kaca menjadi produk yang dapat digunakan. Kaca yang dihancurkan dan siap untuk dilebur kembali disebut cullet. Ada dua jenis cullet: internal dan eksternal. Kulkas internal terdiri dari produk cacat yang terdeteksi dan ditolak oleh proses kontrol kualitas selama proses industri pembuatan kaca, fase transisi perubahan produk (seperti ketebalan dan perubahan warna) dan potongan produksi. Cullet eksternal adalah limbah kaca yang telah dikumpulkan atau diolah kembali dengan tujuan untuk didaur ulang. Pembuangan eksternal (yang dapat dilakukan sebelum atau sesudah konsumen) diklasifikasikan sebagai limbah. Kata \"cullet\", bila digunakan dalam konteks end-of-waste, akan selalu mengacu pada cullet eksternal.<br><br>Untuk didaur ulang, limbah kaca perlu dimurnikan dan dibersihkan dari kontaminasi. Kemudian, tergantung pada penggunaan akhir dan kemampuan pemrosesan lokal, mungkin juga harus dipisahkan menjadi warna yang berbeda. Banyak pendaur ulang mengumpulkan warna kaca yang berbeda secara terpisah karena kaca mempertahankan warnanya setelah didaur ulang.",
	"bYVih298o1Y", "6R8YObQbE88"],
"Bola Lampu":
	["Daur ulang mencegah pelepasan bahan berbahaya ke lingkungan. Merkuri, logam berat yang sangat beracun, digunakan dalam bola lampu neon untuk meningkatkan efisiensi energi. Selain merkuri, beberapa lampu HID mengandung zat radioaktif seperti Krypton-85 dan thorium yang digunakan untuk penyalaan cahaya yang cepat dan mudah.<br><br>LED di sisi lain tidak mengandung merkuri; tapi, mereka memang mengandung nikel, timbal, dan sejumlah kecil arsenik. Bola lampu sering pecah saat dibuang ke tempat sampah, tempat sampah atau pemadat, atau saat berakhir di tempat pembuangan sampah atau insinerator. Hal ini menyebabkan pelepasan bahan berbahaya ke lingkungan dan dapat menimbulkan masalah kesehatan masyarakat dan lingkungan yang serius.<br><br>Penting juga untuk diingat bahwa daur ulang memungkinkan penggunaan kembali kaca, logam, dan bahan lain yang membentuk bola lampu. Hampir semua komponen bola lampu dapat didaur ulang.",
	"nQ3pq8sEzYU", "PkfX4sZwrQ4"],
"Metal":
	["Beberapa jenis dan juga sejumlah besar logam digunakan dalam proses industri setiap hari. Sejak masa revolusi industri terjadi, tingkat konsumsi kita meroket karena produksi massal barang dan harga satuan yang dihasilkan rendah.<br><br>Logam yang paling banyak dikonsumsi di seluruh dunia adalah aluminium, diikuti oleh tembaga, seng, timah, dan nikel . Selain itu, beberapa bahan berharga seperti emas digunakan untuk komputer dan perangkat elektronik lainnya.<br><br>Oleh karena itu, logam sangat penting untuk menopang standar hidup kita. Namun, logam adalah sumber daya yang terbatas. Penipisan logam dapat menjadi masalah besar di masa depan karena populasi dunia tumbuh pesat dan dengan demikian juga permintaan barang yang terbuat dari logam akan meningkat.<br><br>Untuk mengurangi masalah penipisan logam, kita harus melihat untuk langkah-langkah yang efektif. Salah satu tindakan tersebut adalah daur ulang logam.",
	"qAGCI0-pQ3E", "rgEEXhbar3A"],
"Organic":
	["Sampah organik mengandung bahan-bahan yang berasal dari organisme hidup. Ada banyak jenis limbah organik dan dapat ditemukan di limbah padat perkotaan, limbah padat industri, limbah pertanian, dan air limbah. Sampah organik sering dibuang bersama sampah lain di tempat pembuangan akhir atau insinerator, tetapi karena dapat terurai secara hayati , beberapa sampah organik cocok untuk pengomposan dan aplikasi lahan.<br><br>Bahan organik yang ditemukan di sampah padat kota meliputi makanan, kertas, kayu , limbah lumpur , dan limbah pekarangan . Karena kekurangan kapasitas TPA baru-baru ini, jumlah tempat pengomposan kota untuk sampah halaman meningkat di seluruh negeri, seperti juga jumlah warga yang membuat kompos sampah halaman di halaman belakang mereka. Pada basis yang lebih terbatas, beberapa pengomposan sampah kota campuran juga dilakukan. Dalam sistem ini, upaya untuk menghilangkan bahan anorganik dilakukan sebelum pengomposan.<br><br>Sisa makanan dari restoran dan toko kelontong biasanya dibuang melalui pembuangan sampah, oleh karena itu, menjadi komponen air limbah dan lumpur limbah.",
	"lHyL41grGUo", "2I8Tjb4Fy-Q"],
"Kertas":
	["Daur ulang kertas adalah proses dimana kertas bekas diubah menjadi produk kertas baru. Ini memiliki sejumlah manfaat penting: Menghemat kertas bekas dari menempati rumah orang dan menghasilkan metana saat terurai. Karena serat kertas mengandung karbon (awalnya diserap oleh pohon dari mana ia diproduksi), daur ulang membuat karbon terkunci lebih lama dan keluar dari atmosfer. Sekitar dua pertiga dari semua produk kertas di AS sekarang diperoleh dan didaur ulang, meskipun tidak semuanya menjadi kertas baru. Setelah pemrosesan berulang, serat menjadi terlalu pendek untuk produksi kertas baru - inilah mengapa serat murni (dari pohon yang dibudidayakan secara berkelanjutan) sering ditambahkan ke resep bubur kertas.<br><br>Daur ulang kertas berkaitan dengan proses pemrosesan ulang kertas bekas untuk digunakan kembali. Kertas bekas dapat diperoleh dari sisa kertas pabrik kertas, bahan kertas bekas, dan bahan kertas bekas yang dibuang setelah digunakan oleh konsumen. Contoh kertas daur ulang yang umum dikenal adalah koran dan majalah bekas.",
	"jAqVxsEgWIM", "xhW0RTg8kRI"],
"Plastic":
	["Daur ulang plastik adalah proses pemulihan skrap atau limbah plastik dan mengolah kembali bahan tersebut menjadi produk yang bermanfaat. Karena simbol yang sengaja menyesatkan pada kemasan plastik dan berbagai rintangan teknis, kurang dari 10% plastik yang pernah didaur ulang. Dibandingkan dengan daur ulang logam yang menguntungkan, dan serupa dengan daur ulang kaca yang bernilai rendah, daur ulang polimer plastik seringkali lebih menantang karena kepadatannya yang rendah dan nilainya yang rendah.<br><br>Fasilitas pemulihan bahan bertanggung jawab untuk menyortir dan memproses plastik. Pada 2019, karena keterbatasan dalam kelayakan ekonominya, fasilitas ini telah berjuang untuk memberikan kontribusi yang berarti bagi rantai pasokan plastik. Industri plastik telah mengetahui setidaknya sejak tahun 1970-an bahwa daur ulang sebagian besar plastik tidak mungkin dilakukan karena keterbatasan ini. Namun, industri telah melobi untuk perluasan daur ulang sementara perusahaan-perusahaan ini terus meningkatkan jumlah plastik murni yang diproduksi.",
	"rYwBL_6hB2I", "I_fUpP-hq3A"]
}


def load_artifacts():
    global model
    model = tf.keras.models.load_model("classifyWaste.h5")

def classify_waste(image_path):
	global model, output_class
	test_image = tf.keras.preprocessing.image.load_img(image_path, target_size=(224, 224))
	test_image = tf.keras.preprocessing.image.img_to_array(test_image) / 255
	test_image = np.expand_dims(test_image, axis = 0)
	predicted_array = model.predict(test_image)
	predicted_value = output_class[np.argmax(predicted_array)]
	return predicted_value, data[predicted_value][0], data[predicted_value][1], data[predicted_value][2]

